module Chate {
  interface Chat {
    void sendMessage(in string username, in string message);
    string receiveMessage();
    void joinChat(in string username);
    void leaveChat(in string username);
    string listUsers();
  };
};

