# DO NOT EDIT THIS FILE!
#
# Python module Chat__POA generated by omniidl

import omniORB
omniORB.updateModule("Chate__POA")

# ** 1. Stub files contributing to this module
import chat_idl

# ** 2. Sub-modules

# ** 3. End